- name: collect a list of the datacenters
  hosts: all
  collections:
    - vmware.vmware_rest
    
    
  tasks:
    - name: datacenter info
      vmware.vmware_rest.vcenter_datacenter_info:
      register: my_datacenters

