- name: Hello World Sample
  hosts: all
  collections: vmware.vmware_rest
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
     
- name: collect a list of the datacenters
  vmware.vmware_rest.vcenter_datacenter_info:
  register: my_datacenters
    

