- name: Hello World Sample
  hosts: all
  collections:
    - vmware.vmware_rest
  
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Collect the list of the existing VM
      vmware.vmware_rest.vcenter_vm_info:
      register: existing_vms
      until: existing_vms is not failed
    

